version: "3"
services:

  dev-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    command: "npm run start-dev"
    env_file:
      - .env
    volumes:
    - ./server/src:/home/node/app/server/src
    - ./common/src:/home/node/app/common/src
    - ./dist:/home/node/app/dist
    ports:
    - "${PORT:-3000}:${PORT:-3000}"
    - "9229:9229"
    depends_on:
      - mongodb
      - redis
      - dev-builder
    networks:
      - rpgtools

  prod-server:
    image: zachanator070/rpgtools:latest
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - mongodb
      - redis
    networks:
      - rpgtools

  dev-builder:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    env_file:
     - .env
    volumes:
     - ./app/src:/home/node/app/app/src
     - ./common/src:/home/node/app/common/src
     - ./dist:/home/node/app/app/dist
    command: "npm run start-dev"
    networks:
     - rpgtools

  prod-builder:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    user: ${CURRENT_UID}
    environment:
      - BUILD_WITH_STATS=${BUILD_WITH_STATS}
    volumes:
     - ./dist:/home/node/app/app/dist
    networks:
     - rpgtools

  mongodb:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_DATABASE: 'rpgtools'
    volumes:
      - ./dev/mongodb-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      rpgtools:

  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    networks:
      rpgtools:

  test-db:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_DATABASE: 'rpgtools'
    ports:
      - "27017:27017"
    networks:
      rpgtools:
        aliases:
          - "mongodb"

networks:
  rpgtools:
