version: "3"
services:

  dev-server:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    command: "npm run start-dev"
    env_file:
      - .env
    volumes:
    - ./src:/home/node/app/src
    - ./dist:/home/node/app/dist
    ports:
    - "${PORT:-3000}:${PORT:-3000}"
    - "9229:9229"
    depends_on:
      - mongodb
      - dev-builder
    networks:
      - rpgtools

  prod-server:
    image: rpgtools
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - mongodb
    networks:
      - rpgtools

  dev-builder:
    build:
      context: .
      dockerfile: src/app/Dockerfile
    env_file:
     - .env
    volumes:
     - ./src:/home/node/app/src
     - ./dist:/home/node/app/dist
    command: "npm run start-dev"
    networks:
     - rpgtools

  prod-builder:
    build:
      context: .
      dockerfile: src/app/Dockerfile
    environment:
      - BUILD_WITH_STATS=${BUILD_WITH_STATS}
    volumes:
     - ./src:/home/node/app/src
     - ./dist:/home/node/app/dist
    networks:
     - rpgtools

  mongodb:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_DATABASE: 'rpgtools'
    volumes:
      - ./dev/mongodb-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      rpgtools:
        aliases:
        - "mongodb"

networks:
  rpgtools:
